"""Mutation check for the safety/research regression tests (developer tool; no broker access).

Each entry removes one fix (a string mutation), runs the regression test that must catch it,
expects a FAILURE, then restores the file with ``git checkout``. Refuses to touch a file that
has uncommitted changes. Usage: ``python tools/mutation_check.py`` from the repo root.
"""
import subprocess
import sys
from pathlib import Path

MUTATIONS = [
    ("stale decision bar refused", "execution/pretrade.py",
     "        if age < 0 or age > ctx.max_bar_age_seconds:", "        if False:",
     "tests/test_paper_execution.py::test_paper_execution_refuses_stale_or_unknown_decision_bars"),
    ("persistent execution lock", "execution/paper.py",
     "        if self.execution_lock.read() is not None:", "        if False:",
     "tests/test_paper_execution.py::test_execution_lock_persists_across_days_until_a_human_clears_it"),
    ("unresolved failure after restart (journal backstop)", "execution/paper.py",
     "        if self.journal.unresolved_failures_on(today):", "        if False:",
     "tests/test_paper_execution.py::test_unresolved_failure_blocks_entries_after_a_restart"),
    ("journal failure after transmit locks", "execution/paper.py",
     '            self._lock(f"paper trade journal write failed after transmission ({status}); entries locked")',
     "            raise",
     "tests/test_paper_execution.py::test_journal_failure_after_transmit_still_confirms_and_locks"),
    ("flattened partial bracket locks", "execution/paper.py",
     '                self._lock(f"paper bracket {parent_id} partially filled and flattened; broker state must be checked")',
     "                pass",
     "tests/test_paper_execution.py::test_flattened_partial_bracket_locks_new_entries"),
    ("lock before journal on failure paths", "execution/paper.py",
     '            self._lock("paper execution transmission error; broker state must be checked")\n            self._record_safely(normalized, "FAILED", reason, None)',
     '            self.journal.record(normalized, status="FAILED", reason=reason)\n            self._lock("paper execution transmission error; broker state must be checked")',
     "tests/test_paper_execution.py::test_failure_paths_lock_even_when_the_journal_is_down"),
    ("merge bars by instant", "run_fetch_journal_bars.py",
     "    by_time = {key(r): r for r in existing}\n    by_time.update({key(r): r for r in fresh})",
     '    by_time = {str(r["time"]): r for r in existing}\n    by_time.update({str(r["time"]): r for r in fresh})',
     "tests/test_replay_parity.py::test_merge_bars_dedupes_the_same_instant_written_differently"),
    ("scorer v3 base = first tradeable price", "research/shadow_scoring.py",
     "    reference = float(bars_after[0].open) if bars_after and float(bars_after[0].open) > 0 else None",
     '    reference = float(row["reference_close"]) if row["reference_close"] is not None else None',
     "tests/test_shadow_scoring.py::test_forward_return_starts_at_the_first_tradeable_price_not_before_the_decision"),
    ("FWD cutoff capped at the deadline", "research/fwd_protocol.py",
     '    days = sorted({_day(r) for r in rows if _day(r) <= EVIDENCE_DEADLINE.isoformat()})',
     '    days = sorted({_day(r) for r in rows})',
     "tests/test_fwd_protocol.py::test_cutoff_never_lands_after_the_deadline"),
    ("preflight drawdown-init check", "execution/preflight.py",
     '        "drawdown_state_initialized", missing is False,', '        "drawdown_state_initialized", True,',
     "tests/test_paper_preflight.py::test_preflight_fails_when_the_drawdown_state_is_missing_for_an_account_with_history"),
    ("cash reserve counts pending", "portfolio/brain.py",
     "        projected_cash = snapshot.cash - snapshot.pending_order_notional - opportunity.proposed_notional",
     "        projected_cash = snapshot.cash - opportunity.proposed_notional",
     "tests/test_portfolio_brain.py::test_pending_entries_count_against_the_cash_reserve"),
    ("candidate liquidity order in replay", "research/pipeline_backtest.py",
     "            pending_decisions.sort(key=lambda x: (x[0], x[1]))",
     "            pending_decisions.sort(key=lambda x: (-x[4].selected.adjusted_score if x[4].selected else 1, x[1]))",
     "tests/test_replay_parity.py::test_capacity_goes_in_the_runtime_liquidity_order_not_by_score"),
    ("bracket protective children GTC", "core/order_manager.py",
     '        bracket.stopLoss.tif = "GTC"', '        bracket.stopLoss.tif = "DAY"',
     "tests/test_paper_execution.py::test_bracket_entry_is_day_but_protective_children_are_gtc"),
    ("kill switch never market-flattens non-stock", "risk/kill_switch.py",
     '            if sec_type != "STK" or qty != int(qty):', "            if False:",
     "tests/test_kill_switch_drill.py::test_kill_switch_never_market_flattens_non_stock_positions"),
    ("executor lifecycle gate", "execution/paper.py",
     "        if status not in self.allowed_strategy_statuses:", "        if False:",
     "tests/test_paper_execution.py::test_autonomous_executor_refuses_strategies_without_paper_status"),
    ("learning off by default", "engine/shadow.py",
     "                 learning_enabled: bool = False, research_execution: bool = False,",
     "                 learning_enabled: bool = True, research_execution: bool = False,",
     "tests/test_shadow_research_path.py::test_learning_is_off_by_default_for_every_runtime_mode"),
    ("selector evaluates only selectable strategies", "engine/strategy_selector.py",
     "                           if status_of(s.name) in SELECTABLE]", "                           ]",
     "tests/test_paper_execution.py::test_selector_never_evaluates_research_or_retired_strategies"),
    ("FWD window restart guard", "run_shadow_only.py",
     '    if record.get("decision_fingerprint") != decision_fingerprint():', "    if False:",
     "tests/test_shadow_only.py::test_shadow_only_refuses_to_restart_on_code_or_config_that_breaks_a_registered_window"),
    ("hard risk default 1%", "config/config.py",
     'getenv("MAX_TRADE_RISK_PCT", "0.01")', 'getenv("MAX_TRADE_RISK_PCT", "0.10")',
     "tests/test_replay_parity.py::test_pipeline_sizes_on_tick_rounded_prices_and_hard_risk_defaults_to_one_percent"),
    ("FWD: single committed registration", "research/fwd_protocol.py",
     "    if len(committed) > 1:", "    if False:",
     "tests/test_fwd_protocol.py::test_second_registration_or_protocol_change_or_ending_never_binds"),
    ("FWD: interim statistics blinded", "research/fwd_protocol.py",
     '    if result["window"].get("binding"):', "    if True:",
     "tests/test_fwd_protocol.py::test_interim_statistics_are_blinded_until_binding"),
    ("FWD: pre-registration look refused", "research/fwd_protocol.py",
     "    if early:", "    if False:",
     "tests/test_fwd_protocol.py::test_cycles_of_the_registered_code_before_the_start_are_a_pre_registration_look"),
    ("kill switch: no flatten under a live opposite order", "risk/kill_switch.py",
     "            if still_working is None or 0 in still_working or con_id(position) in still_working:",
     "            if False:",
     "tests/test_kill_switch_drill.py::test_kill_switch_never_flattens_under_another_clients_live_gtc_stop"),
    ("kill switch: keep protection of manual positions", "risk/kill_switch.py",
     "            if cid in manual_con_ids or (all_orders", "            if (all_orders",
     "tests/test_kill_switch_drill.py::test_kill_switch_keeps_the_protection_of_positions_it_leaves_to_a_human"),
    ("daily-loss baseline rolls per day", "engine/supervisor.py",
     "        self._roll_trading_day(account.net_liquidation)", "        pass",
     "tests/test_guard_interactions.py::test_evaluate_itself_rolls_the_baseline_when_the_date_changes"),
    ("instrument-type universe", "engine/shadow.py",
     "                if stock_type not in TRADABLE_STOCK_TYPES:", "                if False:",
     "tests/test_opportunity.py::test_stock_type_is_journaled_and_non_common_instruments_are_excluded_before_deciding"),
    ("recorder cannot break a decision", "engine/decision.py",
     "        except Exception as exc:", "        except ZeroDivisionError as exc:",
     "tests/test_opportunity.py::test_a_recorder_failure_never_changes_the_decision"),
    ("preflight per-trade risk ceiling", "execution/preflight.py",
     "risk.max_trade_risk_pct <= 0.01,", "True,",
     "tests/test_paper_preflight.py::test_preflight_refuses_a_per_trade_risk_ceiling_looser_than_the_allocator"),
    ("scorer freezes first forward returns", "research/shadow_scoring.py",
     "fwd_5=COALESCE(shadow_outcomes.fwd_5, excluded.fwd_5),", "fwd_5=excluded.fwd_5,",
     "tests/test_shadow_scoring.py::test_first_forward_returns_are_frozen_and_counts_are_blind"),
    ("failed type lookup is a candidate error", "engine/shadow.py",
     "                if not lookup_ok:", "                if False:",
     "tests/test_opportunity.py::test_failed_type_lookup_is_a_candidate_error_not_an_exclusion"),
    ("excluded types do not consume slots", "engine/shadow.py",
     "                analysed += 1", "                pass",
     "tests/test_opportunity.py::test_excluded_types_do_not_consume_deep_analysis_slots"),
    ("candidate error share gate", "research/shadow_quality.py",
     '"BLOCKING" if blocking else "WARNING",', '"WARNING",',
     "tests/test_shadow_quality.py::test_candidate_error_gate_needs_both_an_absolute_and_a_relative_threshold"),
    ("binding result stored", "research/fwd_protocol.py",
     "        if stored is not None:", "        if False:",
     "tests/test_fwd_protocol.py::test_a_stored_binding_result_cannot_be_re_evaluated_away"),
    ("foreign scoring rules block binding", "research/fwd_protocol.py",
     "    binding = (reached or deadline_passed) and unscored == 0 and foreign == 0",
     "    binding = (reached or deadline_passed) and unscored == 0",
     "tests/test_fwd_protocol.py::test_rows_scored_by_other_rules_block_binding"),
    ("kill switch fails closed without the every-client view", "risk/kill_switch.py",
     "            if still_working is None or 0 in still_working or con_id(position) in still_working:",
     "            if still_working is not None and con_id(position) in still_working:",
     "tests/test_kill_switch_drill.py::test_kill_switch_fails_closed_when_the_every_client_view_is_unavailable"),
    ("kill switch cancels only own-client orders", "risk/kill_switch.py",
     "            if own is not None and isinstance(order_client, int) and order_client != own:", "            if False:",
     "tests/test_kill_switch_drill.py::test_kill_switch_never_cancels_another_clients_order_ids"),
    ("failed day roll keeps the guard running", "engine/supervisor.py",
     '            logger.critical("SUPERVISOR DAY ROLL FAILED | entries locked; guard keeps the last baseline | %s",',
     '            raise RuntimeError("mutant"); logger.critical("x %s",',
     "tests/test_guard_interactions.py::test_a_failed_day_roll_never_stops_the_daily_guard_or_kill_switch"),
    ("kill switch keeps own stop without the every-client view", "risk/kill_switch.py",
     " or (all_orders is None and (cid == 0 or cid in position_ids)):", ":",
     "tests/test_kill_switch_drill.py::test_kill_switch_keeps_own_stop_when_the_every_client_view_is_unavailable"),
    ("kill switch: no flatten decision without the every-client view", "risk/kill_switch.py",
     '                reason_skip = "every-client view unavailable"', "                pass",
     "tests/test_kill_switch_drill.py::test_kill_switch_keeps_own_stop_when_the_every_client_view_is_unavailable"),
    ("kill switch keeps own stop under a foreign order", "risk/kill_switch.py",
     "            elif con_id(position) == 0 or 0 in foreign_con_ids or con_id(position) in foreign_con_ids:",
     "            elif False:",
     "tests/test_kill_switch_drill.py::test_kill_switch_keeps_own_stop_when_another_client_works_the_same_contract"),
    ("kill switch never cancels its own liquidation", "risk/kill_switch.py",
     '            if int(getattr(trade.order, "orderId", 0) or 0) in self._liquidation_order_ids:
                continue',
     "            pass",
     "tests/test_kill_switch_drill.py::test_kill_switch_rerun_never_cancels_or_duplicates_its_own_pending_liquidation"),
    ("candidate error gate absolute minimum", "research/shadow_quality.py",
     "blocking = errors_n >= MIN_CANDIDATE_ERRORS_BLOCKING and share", "blocking = share",
     "tests/test_shadow_quality.py::test_candidate_error_gate_needs_both_an_absolute_and_a_relative_threshold"),
    ("candidate error share over analysable names", "research/shadow_quality.py",
     "base = max(1, attempted - excluded)", "base = max(1, attempted)",
     "tests/test_shadow_quality.py::test_type_excluded_names_do_not_dilute_the_candidate_error_share"),
    ("acceptance ref read from the registration", "research/fwd_protocol.py",
     'pushed = committed_registrations(ref=registration.get("acceptance_ref") or DEFAULT_ACCEPTANCE_REF)',
     'pushed = committed_registrations(ref="origin/main")',
     "tests/test_fwd_protocol.py::test_the_acceptance_ref_is_the_integration_branch_and_is_recorded_in_the_registration"),
    ("first accepted commit time stored", "research/fwd_protocol.py",
     "    _record_acceptance(path, commit_time)", "    pass",
     "tests/test_fwd_protocol.py::test_the_first_accepted_commit_time_is_stored_and_survives_a_later_rewrite"),
    ("scorer refuses foreign rules inside a window", "research/shadow_scoring.py",
     "        refusal = self._window_refusal()
        if refusal:", "        refusal = self._window_refusal()
        if False:",
     "tests/test_shadow_scoring.py::test_scoring_inside_a_registered_window_requires_the_registered_rules"),
    ("registration needs a fresh journal", "run_shadow_only.py",
     '                    return "this journal already holds cycles of this code: use a FRESH KNT_STATE_DIR"',
     "                    pass",
     "tests/test_shadow_only.py::test_registration_refuses_until_every_pre_registration_condition_holds"),
]

ok = True
for name, path, old, new, test in MUTATIONS:
    p = Path(path)
    if subprocess.run(["git", "diff", "--quiet", "--", path]).returncode != 0:
        print(f"SKIP  | {name} | {path} has uncommitted changes")
        ok = False
        continue
    text = p.read_text(encoding="utf-8")
    if old not in text:
        print(f"SKIP  | {name} | pattern not found")
        ok = False
        continue
    p.write_text(text.replace(old, new, 1), encoding="utf-8")
    try:
        r = subprocess.run([sys.executable, "-m", "pytest", "-q", test], capture_output=True, text=True)
        verdict = "KILLED" if r.returncode != 0 else "SURVIVED"
        ok &= verdict == "KILLED"
        print(f"{verdict} | {name} | {test.split('::')[1]}")
    finally:
        subprocess.run(["git", "checkout", "--", path], check=True)
print("ALL MUTATIONS KILLED" if ok else "SOME MUTATIONS NOT KILLED")
sys.exit(0 if ok else 1)
